"""empty message

Revision ID: 7fbc72ff8e6b
Revises: 69f955da12a3
Create Date: 2017-10-07 23:59:26.371764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbc72ff8e6b'
down_revision = '69f955da12a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'enabled')
    # ### end Alembic commands ###
